### ISSUE TITLE
[Feature]: De-redundanize NNIDs

### ISSUE THREAD

**Issue by CCIGAMES** [PretendoNetwork/account#115]
### Checked Existing

- [x] I have checked the repository for duplicate issues.

### What feature do you want to see added?

Surely it is possible for Pretendo to do a simple account check where it looks at the user, sees their id, checks if it's a PNID, which it then goes through all the normal processes, and if it isnt registered as a PNID, then it assumes its an NNID and lets the user access the content?
![image](https://github.com/user-attachments/assets/9a3dc9dd-4492-4106-a929-2a64b4911248)

or maybe like a mirror PNID of the users NNID is made automatically so when the user uses their NNID for anything Pretendo, it ust works as a PNID.

Words of warning, if you get confused or doubtful of this, it isnt because it's not possible, its for sure because I havent explained it well at all

### Why do you want to have this feature?

Because many people dont want to give up their NNID's with all their saves and it's "official-ness" for a server revival project still in it's early stages, why create a whole separate PNID when there should certainly be workarounds that could be used for NNIDs, or at least a way to log into a PNID with an NNID, (hell maybe the Nintendo api supports that, probably not though, although that being said there are many fanmade things that are todo with the 3ds/wii u and Nintendo Network)

### Any other details to share? (OPTIONAL)

Theres alot of repos from what I've seen that could be helpful to revive the use of NNIDs, I wont bombard you with them here since I want you to look at the ones you think are best for the job rather than follow a LQ repo's codebase which could bugger up Pretendo in future.

**Comment by jonbarrow** [comment]
Only Nintendo has access to your data. We do not. We cannot just let accounts access our services without proper authentication. Even projects like rverse did not do real authentication with NNIDs, they simply looked at static regions of service tokens from Nintendo which could be used to identify a specific account. But only if you already knew who the token was supposed to be for. This is not something we are going to put energy into, and is already mentioned in our FAQ.

![Screenshot from 2024-09-14 14-01-52](https://github.com/user-attachments/assets/ba512a4e-1d69-4a1c-856d-c61d0e725bd5)

**Comment by CCIGAMES** [comment]
I understand it's already mentioned on your FAQ, and that you dont want to do it, but there are so many workarounds to it that just saying "it's too hard to bother with" isnt everything, it is certainly doable, I understand this project is worked on in people's free time and is very early in it's life, but that doesnt require/mean scrapping the idea.

**Comment by jonbarrow** [comment]
No one said it was "too hard to bother with". We said it's not something we are interested in and the "workarounds" you mentioned are half-baked and non-viable. We can't just "let the NNID onto our servers", that's not how any of this works. We can only allow connections from clients which pass our authentication. If they don't pass our authentication, we can't securely handle the user. Allowing essentially unauthenticated access to the servers, as you've proposed, completely breaks down the entire authentication system. Not to mention that this would create a ton of overlap between data which is supposed to be unique, as now it would be mixing the data of multiple platforms into one source. Even the "mirror account" suggestion is not viable. You can create a PNID using the exact same username and password as a NNID, and it still would not authenticate with our servers because of how NNID authentication is implemented. Your password is never actually sent to the servers when logging in. Instead a pre-hashed version is sent. This hash is created from your plaintext password and a salt, which is partially made up of your unique PID (the ID assigned to your user account). You would need an account that has the same username, password, AND user PID in order for that to work. But obviously this would never be the case, since IDs are not going to be the same. The same goes for game servers. Your NNID is *NOT* what is used to login to game servers. Instead it is a specific "game server account", which is *tied* to your NNID. This account has a PID as well and its own separate password. This password is, again, never actually sent to the game server. The game server is assumed to *already* know the users game server account password, and that password is used by both the client and server to compute a shared key used to validate connection tickets. This system is only possible if our servers already know what each user's password should be, which we obviously don't know for NNIDs so we wouldn't be able to compute this shared key and pass the ticket validation. The only way for us to get knowledge of this data is to basically act as the NNID on our servers and make requests to NNAS on the NNIDs behalf. Which is something we are not interested in doing, as it just over complicates things for no real reason and would require us to have knowledge of sensitive user information like the user's NNID password. None of that is data we wish to handle, ***which was already stated in the FAQ***

It's not "too hard to deal with". It's not something we're putting time into because it has very little REAL benefits (yes, people could use a NNID, but you can just as easily make a PNID and move your save files. Your save data stored on Nintendo's servers would never have been accessible anyway, only your local saves, so just move them with something like SaveMii. Just make a PNID), at the cost of having more complex/bloated server interactions which is more annoying to maintain long term and worse authentication. The benefits (if you could really call them benefits) do not come close to outweighing the cons here

There is a scope we abide by and this is not within scope. Not every idea is going to be accepted, and I've already laid out the reasons (mutliple times now) as to why

**Comment by CCIGAMES** [comment]
Ig, however you're turning away quite a few people that want to keep their official NNIDs rather than settle for a fake (some of those guys have the oddly specific fear that Nintendo will just suddenly support NNID related stuff again and the whole PNID system breaks).

I believe you could set up an easier system, not exactly like a mirror account because of all the reasons you've mentioned before, but something that effectively looks like that to the user, something like Automated SaveMii with a couple of extra steps for multiplayer.

**Comment by jonbarrow** [comment]
> however you're turning away quite a few people that want to keep their official NNIDs

Sucks, it's a different server network with a different account system. You don't get mad at Google for not letting you use Twitter as your YouTube account. We are not NNIDs. We are our own servers

> rather than settle for a fake

It's not a "fake". It's a different account system entirely. These aren't "fake NNIDs". They're real accounts on our separate network

> and the whole PNID system breaks

This literally makes no sense whatsoever. Nintendo literally still supports NNIDs, you can login with a NNID right now and still connect to the Wii U/3DS friends servers as well as Pokemon Bank on the 3DS, and download your eShop titles from your NNID. Also Pretendo has existed for almost a decade, work began in 2017. That was long before the shut down, well into the time when Nintendo Network was still thriving. And there was no "breaking of the PNID system", *because it's entirely separate servers*

> I believe you could set up an easier system, not exactly like a mirror account because of all the reasons you've mentioned before, but something that effectively looks like that to the user, something like Automated SaveMii with a couple of extra steps for multiplayer.

Talk is cheap. I've already explained why this doesn't work the way you want it to, if you won't accept that then that's on you at this point. Literally just make a PNID and use SaveMii. There is no viable steps to do this for "multiplayer", which again *I have already explained multiple times*. Go reread the reasons I've already explained

There is nothing left to be said about the subject. All the information and answers you could need is already here. If you choose to not believe them, then that's on you

**Comment by CCIGAMES** [comment]
all i am saying is that it is (in some way) doable to an extent.
I understand it's a pain in the ass to do, but I'm just saying to not disregard the og IDs entirely

**Comment by jonbarrow** [comment]
I'm locking this. We're going in circles, read what I've said already. Nintendo Network IDs use an entirely different account system. This isn't going to happen, and if you refuse to read the reasons why then that's on you. I'm not putting any more effort into this.
