### ISSUE TITLE
Implement password change

### ISSUE THREAD

**Issue by InternalLoss** [PretendoNetwork/account#24]
When changing a password, the console checks that the NNID password you provide is correct - if so, it'll PUT to `https://account.nintendo.net/v1/api/people/@me/`:
```xml
<person>
	<password>{PLAINTEXT PASSWORD}</password>
</person>
```

with HTTP 200 sent.

(NB: should we check if passwords are in known data breaches? i.e. using pwnedpasswords SHA-1 api)

**Comment by jonbarrow** [comment]
> (NB: should we check if passwords are in known data breaches? i.e. using pwnedpasswords SHA-1 api)

This sounds like a good idea but is probably pretty limiting. We don't have the same freedoms as we do on the web, the WiiU won't accept any password with any characters at any length. I think adding more constraints than necessary would only cause more issues. Especially if we have no clear way of telling users "this password was found in a data breach", since I doubt Nintendo has an error built in for that and sending a generic error would just confuse users

**Comment by InternalLoss** [comment]
I understand that, it was just a thought is all :)
