### ISSUE TITLE
3DS accounts aren't able to update eShop info

### ISSUE THREAD

**Issue by InternalLoss** [PretendoNetwork/account#29]
When linking, the 3DS sends the following as `POST https://account.pretendo.cc/v1/api/people/@me/devices/@current/attributes`:
```xml
<device_attributes>
	<device_attribute>
		<name>uuid_account</name>
		<value>{UUID 1}</value>
	</device_attribute>
	<device_attribute>
		<name>uuid_common</name>
		<value>{UUID 2}</value>
	</device_attribute>
	<device_attribute>
		<name>ctr_nex_account</name>
		<value>{NEX ACC}</value>
	</device_attribute>
	<device_attribute>
		<name>ctr_nex_password</name>
		<value>{NEX PW}</value>
	</device_attribute>
	<device_attribute>
		<name>ctr_nex_environment</name>
		<value>L1</value>
	</device_attribute>
	<device_attribute>
		<name>persistent_id</name>
		<value>00000000</value>
	</device_attribute>
	<device_attribute>
		<name>transferable_id_base</name>
		<value>0000000000000000</value>
	</device_attribute>
	<device_attribute>
		<name>transferable_id_base_common</name>
		<value>0000000000000000</value>
	</device_attribute>
</device_attributes>
```

Currently, Pretendo sends a 404.

**Comment by jonbarrow** [comment]
I have models for these things written up already I just never properly implemented them. I'm trying to think of where the best place to store this data would be

Obviously the first choice would be with the device data but there's a few issues with doing that atm. Right now the account server doesn't handle Wii U devices _at all_. We only make new device entries for 3DS accounts. Also I've seen device attributes be sent with the Wii U as well and I remember seeing some `ctr` stuff in there. So when you link a NNID to a 3DS does the NNID api now send these attributes as well even when on the Wii U? If so it might make more sense to store this data on the NNID instead of the device. Otherwise we'd have to do some overhead when it comes to linking multiple devices and their data to a NNID

**Comment by InternalLoss** [comment]
Wii U definitely sends attributes too, but the Wii U isn't sent CTR information last I checked - I can double check against my own captures when I'm at home, but it definitely wouldnt be sending the 3DS' NEX account/etc

As said previously, this would probably need to be per-device, since then we can also assign the owner PNID's PID

**Comment by InternalLoss** [comment]
So, if a 3DS is connected to the NNID, the following attributes are added:
```xml
            <attributes>
                <attribute>
                    <id>95864170</id>
                    <name>ctr_initial_device_account_id</name>
                    <updated_by>USER</updated_by>
                    <value>XXX</value>
                </attribute>
                <attribute>
                    <id>95864088</id>
                    <name>environment</name>
                    <updated_by>USER</updated_by>
                    <value>PROD</value>
                </attribute>
            </attributes>
```

These values are **NOT PRESENT** if the eShop has not been opened on a 3DS.

**Comment by jonbarrow** [comment]
> These values are NOT PRESENT if the eShop has not been opened on a 3DS - persistent id, transferable id (base and base_common) are both empty but uuid account and uuid common are NOT.

Okay so given that we don't support the eShop on either platform atm (and likely never will), I believe it's safe to ignore these and only send each console it's specific attributes

**Comment by jonbarrow** [comment]
Bumping this with another question. How important are these values? Are these only shop related? If so I'm not sure it's important to support them given that we don't support the eShop. I haven't been sending this values to the Wii U since the beginning and have seen no bad side effects from doing so

**Comment by InternalLoss** [comment]
I would assume they are shop related which is why I'd typically agree this can be safely ignored, but the 3DS _will_ keep sending them until they're sent back for some reason which is just wasted bandwidth/computing time on our side and the user's.

Also of course the CTR NEX account is included and is useful to know

**Comment by jonbarrow** [comment]
I'll leave this open for now since it's _technically_ unimplemented behavior on our end but it's nowhere near my top priority right now

**Comment by jonbarrow** [comment]
Closing due to eShop closure, this is no longer relevant
